### ISSUE TITLE
FRR DUT: transmit rate is a limiting factor 

### ISSUE THREAD

**Issue by bortok** [OpenIxia/otg-demo#3]
With rate set as:
````
flows:
- duration:
    choice: fixed_packets
    fixed_packets:
      gap: 12
      packets: 1000000
  metrics:
    enable: true
    loss: false
    timestamps: false
  rate:
    choice: pps
    pps: "100000"
  size:
    choice: fixed
    fixed: 512
````
the limiting factor is TX rate. The DUT passes 100% of the packets
````
2022/05/15 21:45:42 Time passed: 11.080817133s out of 10s
2022/05/15 21:45:42 Stopping traffic...
2022/05/15 21:45:42 Metrics Response:
choice: flow_metrics
flow_metrics:
- bytes_rx: "211071488"
  bytes_tx: "0"
  frames_rx: "412249"
  frames_rx_rate: 33645
  frames_tx: "412249"
  frames_tx_rate: 32901
  name: p1.v4.p2
  transmit: stopped

--- PASS: Test_RTBH_IPv4_Ingress_Traffic (11.14s)
````
